[project]
name = "sunbeam-libraries"
version = "0.1.0"
dependencies = ["sunbeam", "requests"]

[project.scripts]
libraries = "extension:main"

[project.optional-dependencies]
dev = ["black", "isort"]
